-- Create table to store Blinkit sales data
-- All columns are initially created as VARCHAR for easy data loading

CREATE TABLE BLINKIT_SALES (
	ITEM_FAT_CONTENT VARCHAR(100),
	ITEM_IDENTIFIER VARCHAR(100),
	ITEM_TYPE VARCHAR(100),
	OUTLET_ESTABLISHMENT_YEAR VARCHAR(100),
	OUTLET_IDENTIFIER VARCHAR(100),
	OUTLET_LOCATION_TYPE VARCHAR(100),
	OUTLET_SIZE VARCHAR(100),
	OUTLET_TYPE VARCHAR(100),
	ITEM_VISIBILITY VARCHAR(100),
	ITEM_WEIGHT VARCHAR(100),
	SALES VARCHAR(100),
	RATING VARCHAR(100)
);

-- Convert outlet_establishment_year from VARCHAR to INT

ALTER TABLE BLINKIT_SALES
ALTER COLUMN OUTLET_ESTABLISHMENT_YEAR TYPE INT USING OUTLET_ESTABLISHMENT_YEAR::INT;

-- Convert item_visibility to numeric and handle empty values

ALTER TABLE BLINKIT_SALES
ALTER COLUMN ITEM_VISIBILITY TYPE NUMERIC(10, 8) USING NULLIF(ITEM_VISIBILITY, '')::NUMERIC;

-- Convert sales column to numeric and handle empty values

ALTER TABLE BLINKIT_SALES
ALTER COLUMN SALES TYPE NUMERIC(10, 4) USING NULLIF(SALES, '')::NUMERIC;

-- Convert rating to numeric (decimal) and remove spaces or empty values

ALTER TABLE BLINKIT_SALES
ALTER COLUMN RATING TYPE NUMERIC(3, 1) USING NULLIF(TRIM(RATING), '')::NUMERIC;

-- Standardize fat content values: LF / low fat → Low Fat

UPDATE BLINKIT_SALES
SET
	ITEM_FAT_CONTENT = 'Low Fat'
WHERE
	TRIM(LOWER(ITEM_FAT_CONTENT)) IN ('lf', 'low fat');

-- Standardize fat content values: reg / regular → Regular

UPDATE BLINKIT_SALES
SET
	ITEM_FAT_CONTENT = 'Regular'
WHERE
	LOWER(ITEM_FAT_CONTENT) IN ('regular', 'reg');

-- View complete cleaned dataset

SELECT
	*
FROM
	BLINKIT_SALES;

-- Calculate total sales in millions

SELECT
	CAST(SUM(SALES) / 1000000 AS DECIMAL(10, 2)) AS TOTAL_SALES_IN_MILLIONS
FROM
	BLINKIT_SALES;

-- Calculate average sales value

SELECT
	CAST(AVG(SALES) AS DECIMAL(10, 1)) AS AVERAGE_SALES
FROM
	BLINKIT_SALES;

-- Count total number of items (records)

SELECT
	COUNT(*) AS NO_OF_ITEMS
FROM
	BLINKIT_SALES;

-- Calculate average customer rating

SELECT
	CAST(AVG(RATING) AS DECIMAL(10, 2)) AS AVG_RATING
FROM
	BLINKIT_SALES;

-- Sales analysis by outlet location type and item fat content

SELECT
	OUTLET_LOCATION_TYPE,
	ITEM_FAT_CONTENT,
	CAST(SUM(SALES) AS DECIMAL(10, 2)) AS TOTAL_SALES,
	CAST(AVG(SALES) AS DECIMAL(10, 1)) AS AVG_SALES,
	COUNT(*) AS NO_OF_ITEM,
	CAST(AVG(RATING) AS DECIMAL(10, 2)) AS AVG_RATING
FROM
	BLINKIT_SALES
GROUP BY
	OUTLET_LOCATION_TYPE,
	ITEM_FAT_CONTENT
ORDER BY
	TOTAL_SALES DESC;

-- Sales performance by outlet establishment year

SELECT
	OUTLET_ESTABLISHMENT_YEAR,
	CAST(SUM(SALES) AS DECIMAL(10, 2)) AS TOTAL_SALES,
	CAST(AVG(SALES) AS DECIMAL(10, 1)) AS AVG_SALES,
	COUNT(*) AS NO_OF_ITEMS,
	CAST(AVG(RATING) AS DECIMAL(10, 2)) AS AVG_RATING
FROM
	BLINKIT_SALES
GROUP BY
	OUTLET_ESTABLISHMENT_YEAR
ORDER BY
	TOTAL_SALES DESC;

-- Location-wise sales contribution percentage for outlets established in 2022

SELECT
	OUTLET_LOCATION_TYPE,
	CAST(SUM(SALES) AS DECIMAL(10, 2)) AS TOTAL_SALES,
	CAST(
		(SUM(SALES) * 100.0 / SUM(SUM(SALES)) OVER ()) AS DECIMAL(10, 2)
	) AS TOTAL_SALES_PERCENTAGE,
	CAST(AVG(SALES) AS DECIMAL(10, 1)) AS AVG_SALES,
	COUNT(*) AS NO_OF_ITEMS,
	CAST(AVG(RATING) AS DECIMAL(10, 2)) AS AVG_RATING
FROM
	BLINKIT_SALES
WHERE
	OUTLET_ESTABLISHMENT_YEAR = 2022
GROUP BY
	OUTLET_LOCATION_TYPE
ORDER BY
	TOTAL_SALES DESC;

-- Sales performance by outlet type

SELECT Outlet_Type,
       CAST(SUM(Sales) AS DECIMAL(10,2)) AS Total_Sales,
       CAST((SUM(Sales) * 100.0 / SUM(SUM(Sales)) OVER()) AS DECIMAL(10,2)) 
           AS Total_Sales_Percentage,
       CAST(AVG(Sales) AS DECIMAL(10,1)) AS Avg_Sales,
       COUNT(*) AS No_Of_Items,
       CAST(AVG(Rating) AS DECIMAL(10,2)) AS Avg_Rating
FROM Blinkit_Sales
GROUP BY Outlet_Type
ORDER BY Total_Sales DESC;